Add Webid to contact card
solid/contacts-pane pull request #23
Opened 2020-11-23 11:21 UTC by timbl

Allows you to add someone's solid id to your vcard data about them. When you do then shows their profile after the contact data.  This in turn has a "chat with me" button and so you contacts become a way of doing stuff.

You can add more than one solidid for those who have more than one.  The profiles are concatenated. Each can be collapsed or expanded under users clicking on an icon in the header.

The styling is not perfect but the functionality is overdue.

2020-11-23 14:48 UTC, TallTed requested changes
Minor tweaks to human-focused UI and comment strings

2020-11-23 14:48 UTC, TallTed commented on contactsPane.js
> +          const agenda = [] // sets of statements of same dcoument to delete
```suggestion
          const agenda = [] // sets of statements of same document to delete
```

2020-11-23 14:48 UTC, TallTed commented on contactsPane.js
>                      // If only one group has beeen selected show ACL
```suggestion
                    // If only one group has been selected, show ACL
```

2020-11-23 14:48 UTC, TallTed commented on contactsPane.js
>            refreshFilteredPeople(true) // Active: select person if justone left
```suggestion
          refreshFilteredPeople(true) // Active: select person if just one left
```

2020-11-23 14:48 UTC, TallTed commented on groupMembershipControl.js
> +// Render a control to record the group membetships we have for this agent
```suggestion
// Render a control to record the group memberships we have for this agent
```

2020-11-23 14:48 UTC, TallTed commented on webidControl.js
> +  prompt.textContent = `If you know someones ${WEBID_NOUN} then you can do more stuff with them.
```suggestion
  prompt.textContent = `If you know someone's ${WEBID_NOUN}, you can do more stuff with them.
```

2020-11-23 14:48 UTC, TallTed commented on webidControl.js
> +  To record their ${WEBID_NOUN}, click the plus or drag it onto the plus.`
```suggestion
  To record their ${WEBID_NOUN}, drag it onto the plus, or click the plus 
  to bring up a selector.`
```

2020-11-25 12:04 UTC, michielbdejong approved these changes

2020-11-25 12:15 UTC, merged